version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: loc8_ml
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    links:
      - mysql

  flask_app:
    build: ./
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=loc8_ml
    depends_on:
      - mysql
    volumes:
      - ./app/uploads:/app/app/uploads
      - ./instance:/app/instance

volumes:
  mysql_data:
